package api

import (
	"slices"
	"testing"
	"time"

	"github.com/shopspring/decimal"

	archivev1 "github.com/leedenison/portfoliodb/proto/archive/v1"
	typev1 "github.com/leedenison/portfoliodb/proto/type/v1"
	dbpkg "github.com/leedenison/portfoliodb/server/db"
	"google.golang.org/protobuf/types/known/timestamppb"
)

func mustTime(t *testing.T, s string) time.Time {
	t.Helper()
	v, err := time.Parse(time.RFC3339, s)
	if err != nil {
		t.Fatalf("parse %q: %v", s, err)
	}
	return v
}

// exportPostingFixture is a minimal stored posting, enough to drive the window
// assembly and the grouping key without stating every column.
func exportPostingFixture(broker, groupID, ts string) dbpkg.ExportPosting {
	at, _ := time.Parse(time.RFC3339, ts)
	return dbpkg.ExportPosting{
		Broker:          broker,
		GroupID:         groupID,
		GroupTimestamp:  at,
		Timestamp:       at,
		Account:         "acct",
		AccountType:     "USER",
		TxType:          "BUYSTOCK",
		Description:     "APPLE INC",
		IdentifierType:  "MIC_TICKER",
		IdentifierValue: "AAPL",
		Quantity:        decimal.RequireFromString("10"),
	}
}

// One window per broker, and its period derived from the postings it holds, so
// the window provably contains everything in it. Import replaces a period, so
// two windows naming one broker would delete each other's groups.
func TestTxWindows_OneWindowPerBrokerBoundedByItsOwnRows(t *testing.T) {
	rows := []dbpkg.ExportPosting{
		exportPostingFixture("FIDELITY", "g1", "2024-01-15T10:00:00Z"),
		exportPostingFixture("FIDELITY", "g2", "2024-03-02T14:30:00Z"),
		exportPostingFixture("IBKR", "g3", "2023-06-01T09:00:00Z"),
	}
	got := txWindows(rows, nil, nil)
	if len(got) != 2 {
		t.Fatalf("windows = %d, want 2", len(got))
	}
	if got[0].GetBroker() != typev1.Broker_FIDELITY {
		t.Fatalf("window 0 broker = %s", got[0].GetBroker())
	}
	if want := mustTime(t, "2024-01-15T10:00:00Z"); !got[0].GetPeriodFrom().AsTime().Equal(want) {
		t.Fatalf("period_from = %s, want %s", got[0].GetPeriodFrom().AsTime(), want)
	}
	// Exclusive, and past the last posting's day, so the last posting is inside.
	if want := mustTime(t, "2024-03-03T00:00:00Z"); !got[0].GetPeriodBefore().AsTime().Equal(want) {
		t.Fatalf("period_before = %s, want %s", got[0].GetPeriodBefore().AsTime(), want)
	}
	if got[1].GetBroker() != typev1.Broker_IBKR {
		t.Fatalf("window 1 broker = %s", got[1].GetBroker())
	}
	if want := mustTime(t, "2023-06-02T00:00:00Z"); !got[1].GetPeriodBefore().AsTime().Equal(want) {
		t.Fatalf("window 1 period_before = %s, want %s", got[1].GetPeriodBefore().AsTime(), want)
	}
}

// The window's source names the export rather than an ingestion job. A posting's
// own source, where one was recorded, travels as the domain of its
// BROKER_DESCRIPTION identifier.
func TestTxWindows_SourceNamesTheExport(t *testing.T) {
	got := txWindows([]dbpkg.ExportPosting{exportPostingFixture("FIDELITY", "g1", "2024-01-15T10:00:00Z")}, nil, nil)
	if got[0].GetSource() != "FIDELITY:archive:export" {
		t.Fatalf("source = %q", got[0].GetSource())
	}
}

// Postings sharing a group id share a group_ref, and the ref is numbered within
// the window rather than being the stored id, which is generated by this
// instance and means nothing to another one.
func TestTxWindows_PostingsShareARefByGroup(t *testing.T) {
	rows := []dbpkg.ExportPosting{
		exportPostingFixture("FIDELITY", "44b1f0e2-0000-4000-8000-000000000001", "2024-01-15T10:00:00Z"),
		exportPostingFixture("FIDELITY", "44b1f0e2-0000-4000-8000-000000000001", "2024-01-15T10:00:00Z"),
		exportPostingFixture("FIDELITY", "44b1f0e2-0000-4000-8000-000000000002", "2024-01-16T10:00:00Z"),
	}
	got := txWindows(rows, nil, nil)
	if len(got) != 1 {
		t.Fatalf("windows = %d, want 1", len(got))
	}
	postings := got[0].GetPostings()
	if len(postings) != 3 {
		t.Fatalf("postings = %d, want 3", len(postings))
	}
	want := []string{"g0", "g0", "g1"}
	for i, w := range want {
		if got := postings[i].GetGroupRef(); got != w {
			t.Fatalf("posting %d group_ref = %q, want %q", i, got, w)
		}
	}
}

// The ref restarts at g0 in each window. A window is a replacement scope of its
// own and the key means nothing outside the one it is stated in.
func TestTxWindows_GroupRefsRestartPerWindow(t *testing.T) {
	rows := []dbpkg.ExportPosting{
		exportPostingFixture("FIDELITY", "g1", "2024-01-15T10:00:00Z"),
		exportPostingFixture("IBKR", "g2", "2024-01-16T10:00:00Z"),
	}
	got := txWindows(rows, nil, nil)
	if len(got) != 2 {
		t.Fatalf("windows = %d, want 2", len(got))
	}
	for i, w := range got {
		if ref := w.GetPostings()[0].GetGroupRef(); ref != "g0" {
			t.Fatalf("window %d first group_ref = %q, want g0", i, ref)
		}
	}
}

// A routed residual travels with its group. It is server-generated, but a group
// exported with its residual sums to zero and the balancer routes nothing for a
// commodity that does, so re-importing routes nothing a second time.
func TestTxWindows_CarriesRoutedResiduals(t *testing.T) {
	residual := exportPostingFixture("FIDELITY", "g1", "2024-01-15T10:00:00Z")
	residual.AccountType = "IMBALANCE"
	got := txWindows([]dbpkg.ExportPosting{
		exportPostingFixture("FIDELITY", "g1", "2024-01-15T10:00:00Z"),
		residual,
	}, nil, nil)
	postings := got[0].GetPostings()
	if len(postings) != 2 {
		t.Fatalf("postings = %d, want 2", len(postings))
	}
	if postings[1].GetAccountType() != typev1.AccountType_ACCOUNT_TYPE_IMBALANCE {
		t.Fatalf("account_type = %s, want IMBALANCE", postings[1].GetAccountType())
	}
}

// Absent is not zero. A column that held nothing is left out rather than
// written as an empty string, so a reader can tell "the file does not state it"
// from "it is empty".
func TestPosting_OptionalFieldsWrittenOnlyWhenHeld(t *testing.T) {
	bare := posting(exportPostingFixture("FIDELITY", "g1", "2024-01-15T10:00:00Z"))
	if bare.UnitPrice != nil || bare.TradingCurrency != nil || bare.SettlementCurrency != nil ||
		bare.BrokerRef != nil || bare.CounterpartyAccount != nil || bare.ShareCountBasis != nil {
		t.Fatalf("bare posting states an absent field: %v", bare)
	}

	r := exportPostingFixture("FIDELITY", "g1", "2024-01-15T10:00:00Z")
	price := decimal.RequireFromString("185.9")
	r.UnitPrice = &price
	r.TradingCurrency = "USD"
	r.SettlementCurrency = "GBP"
	r.BrokerRef = "REF-1"
	r.CounterpartyAccount = "other"
	full := posting(r)
	if full.GetUnitPrice() != "185.9" {
		t.Fatalf("unit_price = %q", full.GetUnitPrice())
	}
	if full.GetTradingCurrency() != "USD" || full.GetSettlementCurrency() != "GBP" {
		t.Fatalf("currencies = %q, %q", full.GetTradingCurrency(), full.GetSettlementCurrency())
	}
	if full.GetBrokerRef() != "REF-1" || full.GetCounterpartyAccount() != "other" {
		t.Fatalf("refs = %q, %q", full.GetBrokerRef(), full.GetCounterpartyAccount())
	}
}

// A posting's evidence travels as it was stored: the scope verbatim, FILE
// included, and every match the source declared. Rewriting a scope on the way out
// would throw away what the source said; what an importer can do is stamp its own
// job on the way in.
func TestPosting_CarriesCorrelationsAsStored(t *testing.T) {
	r := exportPostingFixture("FIDELITY", "g1", "2024-01-15T10:00:00Z")
	ordinal, span := int64(971613414), int64(8)
	r.Correlations = []dbpkg.Correlation{
		{Token: "971613414", Ordinal: &ordinal, OrdinalSpan: &span, Scope: "FILE",
			Match: []string{"EXACT", "ORDINAL"}},
		{Label: "counterparty", Token: "AG10000001", Scope: "BROKER", Match: []string{"ACCOUNT"}},
	}
	got := posting(r).GetCorrelations()
	if len(got) != 2 {
		t.Fatalf("correlations = %v, want 2", got)
	}
	ref := got[0]
	if ref.GetLabel() != "" || ref.GetToken() != "971613414" {
		t.Errorf("reference = %q/%q, want \"\"/971613414", ref.GetLabel(), ref.GetToken())
	}
	if ref.GetOrdinal() != ordinal || ref.GetOrdinalSpan() != span {
		t.Errorf("ordinal = %d/%d, want %d/%d", ref.GetOrdinal(), ref.GetOrdinalSpan(), ordinal, span)
	}
	if ref.GetScope() != typev1.Scope_SCOPE_FILE {
		t.Errorf("scope = %v, want SCOPE_FILE", ref.GetScope())
	}
	wantMatch := []typev1.Match{typev1.Match_MATCH_EXACT, typev1.Match_MATCH_ORDINAL}
	if !slices.Equal(ref.GetMatch(), wantMatch) {
		t.Errorf("match = %v, want %v", ref.GetMatch(), wantMatch)
	}
	pointer := got[1]
	if pointer.GetLabel() != "counterparty" || pointer.GetToken() != "AG10000001" {
		t.Errorf("pointer = %q/%q", pointer.GetLabel(), pointer.GetToken())
	}
	if pointer.GetScope() != typev1.Scope_SCOPE_BROKER ||
		!slices.Equal(pointer.GetMatch(), []typev1.Match{typev1.Match_MATCH_ACCOUNT}) {
		t.Errorf("pointer scope/match = %v/%v", pointer.GetScope(), pointer.GetMatch())
	}
	// An opaque identifier has no number in it, and a correlation that names one
	// anyway would invent an ordering the source does not have.
	if pointer.Ordinal != nil || pointer.OrdinalSpan != nil {
		t.Errorf("pointer states an ordinal: %v/%v", pointer.Ordinal, pointer.OrdinalSpan)
	}
}

// The basis is written only where it differs from the posting's own date. The
// query reports as-traded as nil, which is what the great majority of postings
// are, and stamping a redundant date on every one of them would say nothing.
func TestPosting_ShareCountBasisOnlyWhenRestated(t *testing.T) {
	r := exportPostingFixture("FIDELITY", "g1", "2024-01-15T10:00:00Z")
	basis := mustTime(t, "2025-07-01T00:00:00Z")
	r.ShareCountBasis = &basis
	if got := posting(r).GetShareCountBasis(); got != "2025-07-01" {
		t.Fatalf("share_count_basis = %q, want 2025-07-01", got)
	}
}

// A posting whose instrument never resolved has no identifier to name. It
// travels with none and resolves from its description on the way back in, rather
// than carrying an UNSPECIFIED type that would fail validation.
func TestPosting_UnresolvedInstrumentCarriesNoHint(t *testing.T) {
	r := exportPostingFixture("FIDELITY", "g1", "2024-01-15T10:00:00Z")
	r.IdentifierType = ""
	r.IdentifierValue = ""
	if hints := posting(r).GetIdentifierHints(); len(hints) != 0 {
		t.Fatalf("identifier_hints = %v, want none", hints)
	}
}

// The identifier bestIdentifierJoin picked becomes the posting's one hint, with
// its domain, so a broker-description instrument keeps the source it resolved
// under.
func TestPosting_CarriesTheBestIdentifier(t *testing.T) {
	r := exportPostingFixture("FIDELITY", "g1", "2024-01-15T10:00:00Z")
	r.IdentifierType = "BROKER_DESCRIPTION"
	r.IdentifierValue = "APPLE INC"
	r.IdentifierDomain = "Fidelity:web:fidelity-csv"
	hints := posting(r).GetIdentifierHints()
	if len(hints) != 1 {
		t.Fatalf("identifier_hints = %v, want 1", hints)
	}
	want := &archivev1.InstrumentRef{
		Type:   typev1.IdentifierType_BROKER_DESCRIPTION,
		Value:  "APPLE INC",
		Domain: "Fidelity:web:fidelity-csv",
	}
	if hints[0].GetType() != want.GetType() || hints[0].GetValue() != want.GetValue() ||
		hints[0].GetDomain() != want.GetDomain() {
		t.Fatalf("hint = %v, want %v", hints[0], want)
	}
}

// A requested period is the window's period verbatim rather than a bound derived
// from the rows that landed in it. What the export was asked for is what the
// window has to say, because a window is a replacement scope: an importer told a
// narrower period than the one the caller asked for would leave behind whatever
// sat in the difference.
func TestTxWindows_StatesTheRequestedPeriod(t *testing.T) {
	from := timestamppb.New(mustTime(t, "2024-02-01T00:00:00Z"))
	before := timestamppb.New(mustTime(t, "2024-03-01T00:00:00Z"))
	got := txWindows([]dbpkg.ExportPosting{
		exportPostingFixture("FIDELITY", "g1", "2024-02-10T10:00:00Z"),
	}, from, before)

	if len(got) != 1 {
		t.Fatalf("windows = %d, want 1", len(got))
	}
	if !got[0].GetPeriodFrom().AsTime().Equal(from.AsTime()) {
		t.Errorf("period_from = %s, want %s", got[0].GetPeriodFrom().AsTime(), from.AsTime())
	}
	if !got[0].GetPeriodBefore().AsTime().Equal(before.AsTime()) {
		t.Errorf("period_before = %s, want %s", got[0].GetPeriodBefore().AsTime(), before.AsTime())
	}
}

// A bound given on one side only is honoured on that side and derived on the
// other, so "everything since March" states March and stops where the data does.
func TestTxWindows_DerivesTheBoundNotAskedFor(t *testing.T) {
	from := timestamppb.New(mustTime(t, "2024-02-01T00:00:00Z"))
	got := txWindows([]dbpkg.ExportPosting{
		exportPostingFixture("FIDELITY", "g1", "2024-02-10T10:00:00Z"),
	}, from, nil)

	if !got[0].GetPeriodFrom().AsTime().Equal(from.AsTime()) {
		t.Errorf("period_from = %s, want %s", got[0].GetPeriodFrom().AsTime(), from.AsTime())
	}
	if want := mustTime(t, "2024-02-11T00:00:00Z"); !got[0].GetPeriodBefore().AsTime().Equal(want) {
		t.Errorf("period_before = %s, want %s", got[0].GetPeriodBefore().AsTime(), want)
	}
}

// A broker whose rows all fell outside the period gets no window at all. An
// export is a picture of what is stored; an empty window would be an instruction
// to clear the period, which is not what the export was asked to say.
func TestTxWindows_NoWindowForABrokerWithNothingInThePeriod(t *testing.T) {
	from := timestamppb.New(mustTime(t, "2024-02-01T00:00:00Z"))
	before := timestamppb.New(mustTime(t, "2024-03-01T00:00:00Z"))
	// The db layer filters the postings, so a broker outside the period arrives as
	// no rows at all.
	got := txWindows([]dbpkg.ExportPosting{
		exportPostingFixture("FIDELITY", "g1", "2024-02-10T10:00:00Z"),
	}, from, before)

	if len(got) != 1 || got[0].GetBroker() != typev1.Broker_FIDELITY {
		t.Fatalf("windows = %d, want 1 for FIDELITY alone", len(got))
	}
}
