// Code generated by MockGen. DO NOT EDIT.
// Source: db.go
//
// Generated by this command:
//
//	mockgen -source=db.go -destination=mock/db_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	v1 "github.com/leedenison/portfoliodb/proto/api/v1"
	gomock "go.uber.org/mock/gomock"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// AppendValidationErrors mocks base method.
func (m *MockDB) AppendValidationErrors(ctx context.Context, jobID string, errs []*v1.ValidationError) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendValidationErrors", ctx, jobID, errs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendValidationErrors indicates an expected call of AppendValidationErrors.
func (mr *MockDBMockRecorder) AppendValidationErrors(ctx, jobID, errs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendValidationErrors", reflect.TypeOf((*MockDB)(nil).AppendValidationErrors), ctx, jobID, errs)
}

// ComputeHoldings mocks base method.
func (m *MockDB) ComputeHoldings(ctx context.Context, portfolioID string, asOf *timestamppb.Timestamp) ([]*v1.Holding, *timestamppb.Timestamp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComputeHoldings", ctx, portfolioID, asOf)
	ret0, _ := ret[0].([]*v1.Holding)
	ret1, _ := ret[1].(*timestamppb.Timestamp)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ComputeHoldings indicates an expected call of ComputeHoldings.
func (mr *MockDBMockRecorder) ComputeHoldings(ctx, portfolioID, asOf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComputeHoldings", reflect.TypeOf((*MockDB)(nil).ComputeHoldings), ctx, portfolioID, asOf)
}

// CreateJob mocks base method.
func (m *MockDB) CreateJob(ctx context.Context, portfolioID, broker string, periodFrom, periodTo *timestamppb.Timestamp) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJob", ctx, portfolioID, broker, periodFrom, periodTo)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJob indicates an expected call of CreateJob.
func (mr *MockDBMockRecorder) CreateJob(ctx, portfolioID, broker, periodFrom, periodTo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJob", reflect.TypeOf((*MockDB)(nil).CreateJob), ctx, portfolioID, broker, periodFrom, periodTo)
}

// CreatePortfolio mocks base method.
func (m *MockDB) CreatePortfolio(ctx context.Context, userID, name string) (*v1.Portfolio, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePortfolio", ctx, userID, name)
	ret0, _ := ret[0].(*v1.Portfolio)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePortfolio indicates an expected call of CreatePortfolio.
func (mr *MockDBMockRecorder) CreatePortfolio(ctx, userID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePortfolio", reflect.TypeOf((*MockDB)(nil).CreatePortfolio), ctx, userID, name)
}

// DeletePortfolio mocks base method.
func (m *MockDB) DeletePortfolio(ctx context.Context, portfolioID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePortfolio", ctx, portfolioID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePortfolio indicates an expected call of DeletePortfolio.
func (mr *MockDBMockRecorder) DeletePortfolio(ctx, portfolioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePortfolio", reflect.TypeOf((*MockDB)(nil).DeletePortfolio), ctx, portfolioID)
}

// GetJob mocks base method.
func (m *MockDB) GetJob(ctx context.Context, jobID string) (v1.JobStatus, []*v1.ValidationError, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJob", ctx, jobID)
	ret0, _ := ret[0].(v1.JobStatus)
	ret1, _ := ret[1].([]*v1.ValidationError)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetJob indicates an expected call of GetJob.
func (mr *MockDBMockRecorder) GetJob(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJob", reflect.TypeOf((*MockDB)(nil).GetJob), ctx, jobID)
}

// GetOrCreateUser mocks base method.
func (m *MockDB) GetOrCreateUser(ctx context.Context, authSub, name, email string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateUser", ctx, authSub, name, email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateUser indicates an expected call of GetOrCreateUser.
func (mr *MockDBMockRecorder) GetOrCreateUser(ctx, authSub, name, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateUser", reflect.TypeOf((*MockDB)(nil).GetOrCreateUser), ctx, authSub, name, email)
}

// GetPortfolio mocks base method.
func (m *MockDB) GetPortfolio(ctx context.Context, portfolioID string) (*v1.Portfolio, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPortfolio", ctx, portfolioID)
	ret0, _ := ret[0].(*v1.Portfolio)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPortfolio indicates an expected call of GetPortfolio.
func (mr *MockDBMockRecorder) GetPortfolio(ctx, portfolioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPortfolio", reflect.TypeOf((*MockDB)(nil).GetPortfolio), ctx, portfolioID)
}

// GetUserByAuthSub mocks base method.
func (m *MockDB) GetUserByAuthSub(ctx context.Context, authSub string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByAuthSub", ctx, authSub)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByAuthSub indicates an expected call of GetUserByAuthSub.
func (mr *MockDBMockRecorder) GetUserByAuthSub(ctx, authSub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByAuthSub", reflect.TypeOf((*MockDB)(nil).GetUserByAuthSub), ctx, authSub)
}

// ListPendingJobIDs mocks base method.
func (m *MockDB) ListPendingJobIDs(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingJobIDs", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingJobIDs indicates an expected call of ListPendingJobIDs.
func (mr *MockDBMockRecorder) ListPendingJobIDs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingJobIDs", reflect.TypeOf((*MockDB)(nil).ListPendingJobIDs), ctx)
}

// ListPortfolios mocks base method.
func (m *MockDB) ListPortfolios(ctx context.Context, userID string, pageSize int32, pageToken string) ([]*v1.Portfolio, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPortfolios", ctx, userID, pageSize, pageToken)
	ret0, _ := ret[0].([]*v1.Portfolio)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPortfolios indicates an expected call of ListPortfolios.
func (mr *MockDBMockRecorder) ListPortfolios(ctx, userID, pageSize, pageToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPortfolios", reflect.TypeOf((*MockDB)(nil).ListPortfolios), ctx, userID, pageSize, pageToken)
}

// ListTxs mocks base method.
func (m *MockDB) ListTxs(ctx context.Context, portfolioID string, broker *v1.Broker, periodFrom, periodTo *timestamppb.Timestamp, pageSize int32, pageToken string) ([]*v1.PortfolioTx, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTxs", ctx, portfolioID, broker, periodFrom, periodTo, pageSize, pageToken)
	ret0, _ := ret[0].([]*v1.PortfolioTx)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTxs indicates an expected call of ListTxs.
func (mr *MockDBMockRecorder) ListTxs(ctx, portfolioID, broker, periodFrom, periodTo, pageSize, pageToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTxs", reflect.TypeOf((*MockDB)(nil).ListTxs), ctx, portfolioID, broker, periodFrom, periodTo, pageSize, pageToken)
}

// PortfolioBelongsToUser mocks base method.
func (m *MockDB) PortfolioBelongsToUser(ctx context.Context, portfolioID, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PortfolioBelongsToUser", ctx, portfolioID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PortfolioBelongsToUser indicates an expected call of PortfolioBelongsToUser.
func (mr *MockDBMockRecorder) PortfolioBelongsToUser(ctx, portfolioID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PortfolioBelongsToUser", reflect.TypeOf((*MockDB)(nil).PortfolioBelongsToUser), ctx, portfolioID, userID)
}

// ReplaceTxsInPeriod mocks base method.
func (m *MockDB) ReplaceTxsInPeriod(ctx context.Context, portfolioID, broker string, periodFrom, periodTo *timestamppb.Timestamp, txs []*v1.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceTxsInPeriod", ctx, portfolioID, broker, periodFrom, periodTo, txs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceTxsInPeriod indicates an expected call of ReplaceTxsInPeriod.
func (mr *MockDBMockRecorder) ReplaceTxsInPeriod(ctx, portfolioID, broker, periodFrom, periodTo, txs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceTxsInPeriod", reflect.TypeOf((*MockDB)(nil).ReplaceTxsInPeriod), ctx, portfolioID, broker, periodFrom, periodTo, txs)
}

// SetJobStatus mocks base method.
func (m *MockDB) SetJobStatus(ctx context.Context, jobID string, status v1.JobStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetJobStatus", ctx, jobID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetJobStatus indicates an expected call of SetJobStatus.
func (mr *MockDBMockRecorder) SetJobStatus(ctx, jobID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetJobStatus", reflect.TypeOf((*MockDB)(nil).SetJobStatus), ctx, jobID, status)
}

// UpdatePortfolio mocks base method.
func (m *MockDB) UpdatePortfolio(ctx context.Context, portfolioID, name string) (*v1.Portfolio, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePortfolio", ctx, portfolioID, name)
	ret0, _ := ret[0].(*v1.Portfolio)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePortfolio indicates an expected call of UpdatePortfolio.
func (mr *MockDBMockRecorder) UpdatePortfolio(ctx, portfolioID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePortfolio", reflect.TypeOf((*MockDB)(nil).UpdatePortfolio), ctx, portfolioID, name)
}

// UpsertTx mocks base method.
func (m *MockDB) UpsertTx(ctx context.Context, portfolioID, broker string, tx *v1.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTx", ctx, portfolioID, broker, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertTx indicates an expected call of UpsertTx.
func (mr *MockDBMockRecorder) UpsertTx(ctx, portfolioID, broker, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTx", reflect.TypeOf((*MockDB)(nil).UpsertTx), ctx, portfolioID, broker, tx)
}

// MockUserDB is a mock of UserDB interface.
type MockUserDB struct {
	ctrl     *gomock.Controller
	recorder *MockUserDBMockRecorder
}

// MockUserDBMockRecorder is the mock recorder for MockUserDB.
type MockUserDBMockRecorder struct {
	mock *MockUserDB
}

// NewMockUserDB creates a new mock instance.
func NewMockUserDB(ctrl *gomock.Controller) *MockUserDB {
	mock := &MockUserDB{ctrl: ctrl}
	mock.recorder = &MockUserDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDB) EXPECT() *MockUserDBMockRecorder {
	return m.recorder
}

// GetOrCreateUser mocks base method.
func (m *MockUserDB) GetOrCreateUser(ctx context.Context, authSub, name, email string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateUser", ctx, authSub, name, email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateUser indicates an expected call of GetOrCreateUser.
func (mr *MockUserDBMockRecorder) GetOrCreateUser(ctx, authSub, name, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateUser", reflect.TypeOf((*MockUserDB)(nil).GetOrCreateUser), ctx, authSub, name, email)
}

// GetUserByAuthSub mocks base method.
func (m *MockUserDB) GetUserByAuthSub(ctx context.Context, authSub string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByAuthSub", ctx, authSub)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByAuthSub indicates an expected call of GetUserByAuthSub.
func (mr *MockUserDBMockRecorder) GetUserByAuthSub(ctx, authSub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByAuthSub", reflect.TypeOf((*MockUserDB)(nil).GetUserByAuthSub), ctx, authSub)
}

// MockPortfolioDB is a mock of PortfolioDB interface.
type MockPortfolioDB struct {
	ctrl     *gomock.Controller
	recorder *MockPortfolioDBMockRecorder
}

// MockPortfolioDBMockRecorder is the mock recorder for MockPortfolioDB.
type MockPortfolioDBMockRecorder struct {
	mock *MockPortfolioDB
}

// NewMockPortfolioDB creates a new mock instance.
func NewMockPortfolioDB(ctrl *gomock.Controller) *MockPortfolioDB {
	mock := &MockPortfolioDB{ctrl: ctrl}
	mock.recorder = &MockPortfolioDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPortfolioDB) EXPECT() *MockPortfolioDBMockRecorder {
	return m.recorder
}

// CreatePortfolio mocks base method.
func (m *MockPortfolioDB) CreatePortfolio(ctx context.Context, userID, name string) (*v1.Portfolio, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePortfolio", ctx, userID, name)
	ret0, _ := ret[0].(*v1.Portfolio)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePortfolio indicates an expected call of CreatePortfolio.
func (mr *MockPortfolioDBMockRecorder) CreatePortfolio(ctx, userID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePortfolio", reflect.TypeOf((*MockPortfolioDB)(nil).CreatePortfolio), ctx, userID, name)
}

// DeletePortfolio mocks base method.
func (m *MockPortfolioDB) DeletePortfolio(ctx context.Context, portfolioID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePortfolio", ctx, portfolioID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePortfolio indicates an expected call of DeletePortfolio.
func (mr *MockPortfolioDBMockRecorder) DeletePortfolio(ctx, portfolioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePortfolio", reflect.TypeOf((*MockPortfolioDB)(nil).DeletePortfolio), ctx, portfolioID)
}

// GetPortfolio mocks base method.
func (m *MockPortfolioDB) GetPortfolio(ctx context.Context, portfolioID string) (*v1.Portfolio, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPortfolio", ctx, portfolioID)
	ret0, _ := ret[0].(*v1.Portfolio)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPortfolio indicates an expected call of GetPortfolio.
func (mr *MockPortfolioDBMockRecorder) GetPortfolio(ctx, portfolioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPortfolio", reflect.TypeOf((*MockPortfolioDB)(nil).GetPortfolio), ctx, portfolioID)
}

// ListPortfolios mocks base method.
func (m *MockPortfolioDB) ListPortfolios(ctx context.Context, userID string, pageSize int32, pageToken string) ([]*v1.Portfolio, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPortfolios", ctx, userID, pageSize, pageToken)
	ret0, _ := ret[0].([]*v1.Portfolio)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPortfolios indicates an expected call of ListPortfolios.
func (mr *MockPortfolioDBMockRecorder) ListPortfolios(ctx, userID, pageSize, pageToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPortfolios", reflect.TypeOf((*MockPortfolioDB)(nil).ListPortfolios), ctx, userID, pageSize, pageToken)
}

// PortfolioBelongsToUser mocks base method.
func (m *MockPortfolioDB) PortfolioBelongsToUser(ctx context.Context, portfolioID, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PortfolioBelongsToUser", ctx, portfolioID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PortfolioBelongsToUser indicates an expected call of PortfolioBelongsToUser.
func (mr *MockPortfolioDBMockRecorder) PortfolioBelongsToUser(ctx, portfolioID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PortfolioBelongsToUser", reflect.TypeOf((*MockPortfolioDB)(nil).PortfolioBelongsToUser), ctx, portfolioID, userID)
}

// UpdatePortfolio mocks base method.
func (m *MockPortfolioDB) UpdatePortfolio(ctx context.Context, portfolioID, name string) (*v1.Portfolio, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePortfolio", ctx, portfolioID, name)
	ret0, _ := ret[0].(*v1.Portfolio)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePortfolio indicates an expected call of UpdatePortfolio.
func (mr *MockPortfolioDBMockRecorder) UpdatePortfolio(ctx, portfolioID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePortfolio", reflect.TypeOf((*MockPortfolioDB)(nil).UpdatePortfolio), ctx, portfolioID, name)
}

// MockTxDB is a mock of TxDB interface.
type MockTxDB struct {
	ctrl     *gomock.Controller
	recorder *MockTxDBMockRecorder
}

// MockTxDBMockRecorder is the mock recorder for MockTxDB.
type MockTxDBMockRecorder struct {
	mock *MockTxDB
}

// NewMockTxDB creates a new mock instance.
func NewMockTxDB(ctrl *gomock.Controller) *MockTxDB {
	mock := &MockTxDB{ctrl: ctrl}
	mock.recorder = &MockTxDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxDB) EXPECT() *MockTxDBMockRecorder {
	return m.recorder
}

// ListTxs mocks base method.
func (m *MockTxDB) ListTxs(ctx context.Context, portfolioID string, broker *v1.Broker, periodFrom, periodTo *timestamppb.Timestamp, pageSize int32, pageToken string) ([]*v1.PortfolioTx, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTxs", ctx, portfolioID, broker, periodFrom, periodTo, pageSize, pageToken)
	ret0, _ := ret[0].([]*v1.PortfolioTx)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTxs indicates an expected call of ListTxs.
func (mr *MockTxDBMockRecorder) ListTxs(ctx, portfolioID, broker, periodFrom, periodTo, pageSize, pageToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTxs", reflect.TypeOf((*MockTxDB)(nil).ListTxs), ctx, portfolioID, broker, periodFrom, periodTo, pageSize, pageToken)
}

// ReplaceTxsInPeriod mocks base method.
func (m *MockTxDB) ReplaceTxsInPeriod(ctx context.Context, portfolioID, broker string, periodFrom, periodTo *timestamppb.Timestamp, txs []*v1.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceTxsInPeriod", ctx, portfolioID, broker, periodFrom, periodTo, txs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceTxsInPeriod indicates an expected call of ReplaceTxsInPeriod.
func (mr *MockTxDBMockRecorder) ReplaceTxsInPeriod(ctx, portfolioID, broker, periodFrom, periodTo, txs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceTxsInPeriod", reflect.TypeOf((*MockTxDB)(nil).ReplaceTxsInPeriod), ctx, portfolioID, broker, periodFrom, periodTo, txs)
}

// UpsertTx mocks base method.
func (m *MockTxDB) UpsertTx(ctx context.Context, portfolioID, broker string, tx *v1.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTx", ctx, portfolioID, broker, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertTx indicates an expected call of UpsertTx.
func (mr *MockTxDBMockRecorder) UpsertTx(ctx, portfolioID, broker, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTx", reflect.TypeOf((*MockTxDB)(nil).UpsertTx), ctx, portfolioID, broker, tx)
}

// MockHoldingsDB is a mock of HoldingsDB interface.
type MockHoldingsDB struct {
	ctrl     *gomock.Controller
	recorder *MockHoldingsDBMockRecorder
}

// MockHoldingsDBMockRecorder is the mock recorder for MockHoldingsDB.
type MockHoldingsDBMockRecorder struct {
	mock *MockHoldingsDB
}

// NewMockHoldingsDB creates a new mock instance.
func NewMockHoldingsDB(ctrl *gomock.Controller) *MockHoldingsDB {
	mock := &MockHoldingsDB{ctrl: ctrl}
	mock.recorder = &MockHoldingsDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHoldingsDB) EXPECT() *MockHoldingsDBMockRecorder {
	return m.recorder
}

// ComputeHoldings mocks base method.
func (m *MockHoldingsDB) ComputeHoldings(ctx context.Context, portfolioID string, asOf *timestamppb.Timestamp) ([]*v1.Holding, *timestamppb.Timestamp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComputeHoldings", ctx, portfolioID, asOf)
	ret0, _ := ret[0].([]*v1.Holding)
	ret1, _ := ret[1].(*timestamppb.Timestamp)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ComputeHoldings indicates an expected call of ComputeHoldings.
func (mr *MockHoldingsDBMockRecorder) ComputeHoldings(ctx, portfolioID, asOf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComputeHoldings", reflect.TypeOf((*MockHoldingsDB)(nil).ComputeHoldings), ctx, portfolioID, asOf)
}

// MockJobDB is a mock of JobDB interface.
type MockJobDB struct {
	ctrl     *gomock.Controller
	recorder *MockJobDBMockRecorder
}

// MockJobDBMockRecorder is the mock recorder for MockJobDB.
type MockJobDBMockRecorder struct {
	mock *MockJobDB
}

// NewMockJobDB creates a new mock instance.
func NewMockJobDB(ctrl *gomock.Controller) *MockJobDB {
	mock := &MockJobDB{ctrl: ctrl}
	mock.recorder = &MockJobDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobDB) EXPECT() *MockJobDBMockRecorder {
	return m.recorder
}

// AppendValidationErrors mocks base method.
func (m *MockJobDB) AppendValidationErrors(ctx context.Context, jobID string, errs []*v1.ValidationError) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendValidationErrors", ctx, jobID, errs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendValidationErrors indicates an expected call of AppendValidationErrors.
func (mr *MockJobDBMockRecorder) AppendValidationErrors(ctx, jobID, errs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendValidationErrors", reflect.TypeOf((*MockJobDB)(nil).AppendValidationErrors), ctx, jobID, errs)
}

// CreateJob mocks base method.
func (m *MockJobDB) CreateJob(ctx context.Context, portfolioID, broker string, periodFrom, periodTo *timestamppb.Timestamp) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJob", ctx, portfolioID, broker, periodFrom, periodTo)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJob indicates an expected call of CreateJob.
func (mr *MockJobDBMockRecorder) CreateJob(ctx, portfolioID, broker, periodFrom, periodTo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJob", reflect.TypeOf((*MockJobDB)(nil).CreateJob), ctx, portfolioID, broker, periodFrom, periodTo)
}

// GetJob mocks base method.
func (m *MockJobDB) GetJob(ctx context.Context, jobID string) (v1.JobStatus, []*v1.ValidationError, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJob", ctx, jobID)
	ret0, _ := ret[0].(v1.JobStatus)
	ret1, _ := ret[1].([]*v1.ValidationError)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetJob indicates an expected call of GetJob.
func (mr *MockJobDBMockRecorder) GetJob(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJob", reflect.TypeOf((*MockJobDB)(nil).GetJob), ctx, jobID)
}

// ListPendingJobIDs mocks base method.
func (m *MockJobDB) ListPendingJobIDs(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingJobIDs", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingJobIDs indicates an expected call of ListPendingJobIDs.
func (mr *MockJobDBMockRecorder) ListPendingJobIDs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingJobIDs", reflect.TypeOf((*MockJobDB)(nil).ListPendingJobIDs), ctx)
}

// SetJobStatus mocks base method.
func (m *MockJobDB) SetJobStatus(ctx context.Context, jobID string, status v1.JobStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetJobStatus", ctx, jobID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetJobStatus indicates an expected call of SetJobStatus.
func (mr *MockJobDBMockRecorder) SetJobStatus(ctx, jobID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetJobStatus", reflect.TypeOf((*MockJobDB)(nil).SetJobStatus), ctx, jobID, status)
}
