-- Seed CASH instruments and CURRENCY identifiers for resolution (candidate plugin returns currency hint; identifier plugin looks up by CURRENCY).
-- One row per currency in instruments, instrument_identifiers and instrument_listings.
--
-- A cash instrument has a listing degenerately: the currency it holds is the
-- currency it trades in. GBX cash gets a GBX listing and GBP cash a GBP one --
-- they are different instruments, so the currency-family uniqueness index never
-- sees the two together.
--
-- The currency is carried by the seed CTE rather than by a column on instruments,
-- which no longer has one: the line is where a currency lives. Ids are drawn up
-- front so the identifier and the listing find their instrument by key, rather
-- than by matching on a name or by trusting INSERT ... SELECT to preserve order.

WITH seed(id, code, label) AS (
  SELECT gen_random_uuid(), v.code, v.label FROM (VALUES
    ('USD', 'US Dollar'),
    ('EUR', 'Euro'),
    ('JPY', 'Japanese Yen'),
    ('GBP', 'Pound Sterling'),
    ('GBX', 'Penny Sterling'),
    ('CHF', 'Swiss Franc'),
    ('CNY', 'Yuan Renminbi'),
    ('AUD', 'Australian Dollar'),
    ('CAD', 'Canadian Dollar'),
    ('NZD', 'New Zealand Dollar'),
    ('SEK', 'Swedish Krona'),
    ('NOK', 'Norwegian Krone'),
    ('DKK', 'Danish Krone'),
    ('HKD', 'Hong Kong Dollar'),
    ('SGD', 'Singapore Dollar'),
    ('KRW', 'South Korean Won'),
    ('INR', 'Indian Rupee'),
    ('TWD', 'New Taiwan Dollar'),
    ('MXN', 'Mexican Peso'),
    ('BRL', 'Brazilian Real'),
    ('ZAR', 'Rand'),
    ('TRY', 'Turkish Lira'),
    ('RUB', 'Russian Ruble'),
    ('PLN', 'Zloty'),
    ('CZK', 'Czech Koruna'),
    ('HUF', 'Forint'),
    ('RON', 'Romanian Leu'),
    ('BGN', 'Bulgarian Lev'),
    ('HRK', 'Croatian Kuna'),
    ('AED', 'UAE Dirham'),
    ('SAR', 'Saudi Riyal'),
    ('QAR', 'Qatari Riyal'),
    ('KWD', 'Kuwaiti Dinar'),
    ('BHD', 'Bahraini Dinar'),
    ('OMR', 'Rial Omani'),
    ('ILS', 'New Israeli Shekel'),
    ('EGP', 'Egyptian Pound'),
    ('MAD', 'Moroccan Dirham'),
    ('DZD', 'Algerian Dinar'),
    ('TND', 'Tunisian Dinar'),
    ('NGN', 'Naira'),
    ('KES', 'Kenyan Shilling'),
    ('GHS', 'Ghana Cedi'),
    ('ETB', 'Ethiopian Birr'),
    ('UGX', 'Uganda Shilling'),
    ('TZS', 'Tanzanian Shilling'),
    ('XOF', 'CFA Franc BCEAO'),
    ('XAF', 'CFA Franc BEAC'),
    ('ARS', 'Argentine Peso'),
    ('CLP', 'Chilean Peso'),
    ('COP', 'Colombian Peso'),
    ('PEN', 'Sol'),
    ('UYU', 'Uruguay Peso'),
    ('BOB', 'Boliviano'),
    ('PYG', 'Guarani'),
    ('CRC', 'Costa Rican Colon'),
    ('DOP', 'Dominican Peso'),
    ('GTQ', 'Quetzal'),
    ('HNL', 'Lempira'),
    ('NIO', 'Cordoba Oro'),
    ('PAB', 'Balboa'),
    ('JMD', 'Jamaican Dollar'),
    ('TTD', 'Trinidad and Tobago Dollar'),
    ('BBD', 'Barbados Dollar'),
    ('BSD', 'Bahamian Dollar'),
    ('XCD', 'East Caribbean Dollar'),
    ('PKR', 'Pakistan Rupee'),
    ('BDT', 'Taka'),
    ('LKR', 'Sri Lanka Rupee'),
    ('NPR', 'Nepalese Rupee'),
    ('MMK', 'Kyat'),
    ('THB', 'Baht'),
    ('VND', 'Dong'),
    ('MYR', 'Malaysian Ringgit'),
    ('IDR', 'Rupiah'),
    ('PHP', 'Philippine Peso'),
    ('KHR', 'Riel'),
    ('LAK', 'Lao Kip'),
    ('BND', 'Brunei Dollar'),
    ('MOP', 'Pataca'),
    ('KZT', 'Tenge'),
    ('UZS', 'Uzbekistan Sum'),
    ('GEL', 'Lari'),
    ('AMD', 'Armenian Dram'),
    ('AZN', 'Azerbaijani Manat'),
    ('RSD', 'Serbian Dinar'),
    ('UAH', 'Hryvnia'),
    ('MDL', 'Moldovan Leu'),
    ('ISK', 'Iceland Krona'),
    ('ALL', 'Lek'),
    ('MKD', 'Denar'),
    ('BAM', 'Convertible Mark'),
    ('JOD', 'Jordanian Dinar'),
    ('LBP', 'Lebanese Pound'),
    ('IQD', 'Iraqi Dinar'),
    ('IRR', 'Iranian Rial'),
    ('AFN', 'Afghani'),
    ('MUR', 'Mauritius Rupee'),
    ('BWP', 'Pula'),
    ('ZMW', 'Zambian Kwacha'),
    ('AOA', 'Kwanza'),
    ('MZN', 'Mozambique Metical'),
    ('SCR', 'Seychelles Rupee')
  ) AS v(code, label)
), ins AS (
  INSERT INTO instruments (id, asset_class, name)
  SELECT id, 'CASH', label FROM seed
), idents AS (
  INSERT INTO instrument_identifiers (instrument_id, identifier_type, value, canonical)
  SELECT id, 'CURRENCY', code, true FROM seed
)
INSERT INTO instrument_listings (instrument_id, currency)
SELECT id, code FROM seed;

-- Seed FX pair instruments for each non-USD currency above. FX instruments
-- represent exchange rate time series (BASE/USD); their eod_prices.close stores
-- how many USD one unit of the base currency buys.
--
-- An FX instrument's listing carries USD: a listing currency is the currency the
-- line is quoted in, and every pair here is quoted against the USD pivot
-- (adr/0006). Degenerate, like the cash rows above, and coherent for the same
-- reason.
WITH fx_ins AS (
  INSERT INTO instruments (asset_class, name)
  VALUES
    ('FX', 'EUR/USD'),
    ('FX', 'JPY/USD'),
    ('FX', 'GBP/USD'),
    ('FX', 'GBX/USD'),
    ('FX', 'CHF/USD'),
    ('FX', 'CNY/USD'),
    ('FX', 'AUD/USD'),
    ('FX', 'CAD/USD'),
    ('FX', 'NZD/USD'),
    ('FX', 'SEK/USD'),
    ('FX', 'NOK/USD'),
    ('FX', 'DKK/USD'),
    ('FX', 'HKD/USD'),
    ('FX', 'SGD/USD'),
    ('FX', 'KRW/USD'),
    ('FX', 'INR/USD'),
    ('FX', 'TWD/USD'),
    ('FX', 'MXN/USD'),
    ('FX', 'BRL/USD'),
    ('FX', 'ZAR/USD'),
    ('FX', 'TRY/USD'),
    ('FX', 'RUB/USD'),
    ('FX', 'PLN/USD'),
    ('FX', 'CZK/USD'),
    ('FX', 'HUF/USD'),
    ('FX', 'RON/USD'),
    ('FX', 'BGN/USD'),
    ('FX', 'HRK/USD'),
    ('FX', 'AED/USD'),
    ('FX', 'SAR/USD'),
    ('FX', 'QAR/USD'),
    ('FX', 'KWD/USD'),
    ('FX', 'BHD/USD'),
    ('FX', 'OMR/USD'),
    ('FX', 'ILS/USD'),
    ('FX', 'EGP/USD'),
    ('FX', 'MAD/USD'),
    ('FX', 'DZD/USD'),
    ('FX', 'TND/USD'),
    ('FX', 'NGN/USD'),
    ('FX', 'KES/USD'),
    ('FX', 'GHS/USD'),
    ('FX', 'ETB/USD'),
    ('FX', 'UGX/USD'),
    ('FX', 'TZS/USD'),
    ('FX', 'XOF/USD'),
    ('FX', 'XAF/USD'),
    ('FX', 'ARS/USD'),
    ('FX', 'CLP/USD'),
    ('FX', 'COP/USD'),
    ('FX', 'PEN/USD'),
    ('FX', 'UYU/USD'),
    ('FX', 'BOB/USD'),
    ('FX', 'PYG/USD'),
    ('FX', 'CRC/USD'),
    ('FX', 'DOP/USD'),
    ('FX', 'GTQ/USD'),
    ('FX', 'HNL/USD'),
    ('FX', 'NIO/USD'),
    ('FX', 'PAB/USD'),
    ('FX', 'JMD/USD'),
    ('FX', 'TTD/USD'),
    ('FX', 'BBD/USD'),
    ('FX', 'BSD/USD'),
    ('FX', 'XCD/USD'),
    ('FX', 'PKR/USD'),
    ('FX', 'BDT/USD'),
    ('FX', 'LKR/USD'),
    ('FX', 'NPR/USD'),
    ('FX', 'MMK/USD'),
    ('FX', 'THB/USD'),
    ('FX', 'VND/USD'),
    ('FX', 'MYR/USD'),
    ('FX', 'IDR/USD'),
    ('FX', 'PHP/USD'),
    ('FX', 'KHR/USD'),
    ('FX', 'LAK/USD'),
    ('FX', 'BND/USD'),
    ('FX', 'MOP/USD'),
    ('FX', 'KZT/USD'),
    ('FX', 'UZS/USD'),
    ('FX', 'GEL/USD'),
    ('FX', 'AMD/USD'),
    ('FX', 'AZN/USD'),
    ('FX', 'RSD/USD'),
    ('FX', 'UAH/USD'),
    ('FX', 'MDL/USD'),
    ('FX', 'ISK/USD'),
    ('FX', 'ALL/USD'),
    ('FX', 'MKD/USD'),
    ('FX', 'BAM/USD'),
    ('FX', 'JOD/USD'),
    ('FX', 'LBP/USD'),
    ('FX', 'IQD/USD'),
    ('FX', 'IRR/USD'),
    ('FX', 'AFN/USD'),
    ('FX', 'MUR/USD'),
    ('FX', 'BWP/USD'),
    ('FX', 'ZMW/USD'),
    ('FX', 'AOA/USD'),
    ('FX', 'MZN/USD'),
    ('FX', 'SCR/USD')
  RETURNING id, name
), fx_idents AS (
  INSERT INTO instrument_identifiers (instrument_id, identifier_type, value, canonical)
  SELECT id, 'FX_PAIR', REPLACE(name, '/', ''), true FROM fx_ins
)
-- The literal, because every pair here is quoted against the USD pivot and so
-- every one of these lines carries USD.
INSERT INTO instrument_listings (instrument_id, currency)
SELECT id, 'USD' FROM fx_ins;
