-- Seed CASH instruments and CURRENCY identifiers for resolution (description plugin returns currency hint; identifier plugin looks up by CURRENCY).
-- One row per currency in instruments and instrument_identifiers.

WITH ins AS (
  INSERT INTO instruments (asset_class, currency, name)
  VALUES
    ('CASH', 'USD', 'US Dollar'),
    ('CASH', 'EUR', 'Euro'),
    ('CASH', 'JPY', 'Japanese Yen'),
    ('CASH', 'GBP', 'Pound Sterling'),
    ('CASH', 'CHF', 'Swiss Franc'),
    ('CASH', 'CNY', 'Yuan Renminbi'),
    ('CASH', 'AUD', 'Australian Dollar'),
    ('CASH', 'CAD', 'Canadian Dollar'),
    ('CASH', 'NZD', 'New Zealand Dollar'),
    ('CASH', 'SEK', 'Swedish Krona'),
    ('CASH', 'NOK', 'Norwegian Krone'),
    ('CASH', 'DKK', 'Danish Krone'),
    ('CASH', 'HKD', 'Hong Kong Dollar'),
    ('CASH', 'SGD', 'Singapore Dollar'),
    ('CASH', 'KRW', 'South Korean Won'),
    ('CASH', 'INR', 'Indian Rupee'),
    ('CASH', 'TWD', 'New Taiwan Dollar'),
    ('CASH', 'MXN', 'Mexican Peso'),
    ('CASH', 'BRL', 'Brazilian Real'),
    ('CASH', 'ZAR', 'Rand'),
    ('CASH', 'TRY', 'Turkish Lira'),
    ('CASH', 'RUB', 'Russian Ruble'),
    ('CASH', 'PLN', 'Zloty'),
    ('CASH', 'CZK', 'Czech Koruna'),
    ('CASH', 'HUF', 'Forint'),
    ('CASH', 'RON', 'Romanian Leu'),
    ('CASH', 'BGN', 'Bulgarian Lev'),
    ('CASH', 'HRK', 'Croatian Kuna'),
    ('CASH', 'AED', 'UAE Dirham'),
    ('CASH', 'SAR', 'Saudi Riyal'),
    ('CASH', 'QAR', 'Qatari Riyal'),
    ('CASH', 'KWD', 'Kuwaiti Dinar'),
    ('CASH', 'BHD', 'Bahraini Dinar'),
    ('CASH', 'OMR', 'Rial Omani'),
    ('CASH', 'ILS', 'New Israeli Shekel'),
    ('CASH', 'EGP', 'Egyptian Pound'),
    ('CASH', 'MAD', 'Moroccan Dirham'),
    ('CASH', 'DZD', 'Algerian Dinar'),
    ('CASH', 'TND', 'Tunisian Dinar'),
    ('CASH', 'NGN', 'Naira'),
    ('CASH', 'KES', 'Kenyan Shilling'),
    ('CASH', 'GHS', 'Ghana Cedi'),
    ('CASH', 'ETB', 'Ethiopian Birr'),
    ('CASH', 'UGX', 'Uganda Shilling'),
    ('CASH', 'TZS', 'Tanzanian Shilling'),
    ('CASH', 'XOF', 'CFA Franc BCEAO'),
    ('CASH', 'XAF', 'CFA Franc BEAC'),
    ('CASH', 'ARS', 'Argentine Peso'),
    ('CASH', 'CLP', 'Chilean Peso'),
    ('CASH', 'COP', 'Colombian Peso'),
    ('CASH', 'PEN', 'Sol'),
    ('CASH', 'UYU', 'Uruguay Peso'),
    ('CASH', 'BOB', 'Boliviano'),
    ('CASH', 'PYG', 'Guarani'),
    ('CASH', 'CRC', 'Costa Rican Colon'),
    ('CASH', 'DOP', 'Dominican Peso'),
    ('CASH', 'GTQ', 'Quetzal'),
    ('CASH', 'HNL', 'Lempira'),
    ('CASH', 'NIO', 'Cordoba Oro'),
    ('CASH', 'PAB', 'Balboa'),
    ('CASH', 'JMD', 'Jamaican Dollar'),
    ('CASH', 'TTD', 'Trinidad and Tobago Dollar'),
    ('CASH', 'BBD', 'Barbados Dollar'),
    ('CASH', 'BSD', 'Bahamian Dollar'),
    ('CASH', 'XCD', 'East Caribbean Dollar'),
    ('CASH', 'PKR', 'Pakistan Rupee'),
    ('CASH', 'BDT', 'Taka'),
    ('CASH', 'LKR', 'Sri Lanka Rupee'),
    ('CASH', 'NPR', 'Nepalese Rupee'),
    ('CASH', 'MMK', 'Kyat'),
    ('CASH', 'THB', 'Baht'),
    ('CASH', 'VND', 'Dong'),
    ('CASH', 'MYR', 'Malaysian Ringgit'),
    ('CASH', 'IDR', 'Rupiah'),
    ('CASH', 'PHP', 'Philippine Peso'),
    ('CASH', 'KHR', 'Riel'),
    ('CASH', 'LAK', 'Lao Kip'),
    ('CASH', 'BND', 'Brunei Dollar'),
    ('CASH', 'MOP', 'Pataca'),
    ('CASH', 'KZT', 'Tenge'),
    ('CASH', 'UZS', 'Uzbekistan Sum'),
    ('CASH', 'GEL', 'Lari'),
    ('CASH', 'AMD', 'Armenian Dram'),
    ('CASH', 'AZN', 'Azerbaijani Manat'),
    ('CASH', 'RSD', 'Serbian Dinar'),
    ('CASH', 'UAH', 'Hryvnia'),
    ('CASH', 'MDL', 'Moldovan Leu'),
    ('CASH', 'ISK', 'Iceland Krona'),
    ('CASH', 'ALL', 'Lek'),
    ('CASH', 'MKD', 'Denar'),
    ('CASH', 'BAM', 'Convertible Mark'),
    ('CASH', 'JOD', 'Jordanian Dinar'),
    ('CASH', 'LBP', 'Lebanese Pound'),
    ('CASH', 'IQD', 'Iraqi Dinar'),
    ('CASH', 'IRR', 'Iranian Rial'),
    ('CASH', 'AFN', 'Afghani'),
    ('CASH', 'MUR', 'Mauritius Rupee'),
    ('CASH', 'BWP', 'Pula'),
    ('CASH', 'ZMW', 'Zambian Kwacha'),
    ('CASH', 'AOA', 'Kwanza'),
    ('CASH', 'MZN', 'Mozambique Metical'),
    ('CASH', 'SCR', 'Seychelles Rupee')
  RETURNING id, currency
)
INSERT INTO instrument_identifiers (instrument_id, identifier_type, value, canonical)
SELECT id, 'CURRENCY', currency, true FROM ins;
