-- Seed EODHD exchange code to MIC mappings.
-- Generated by local/gen_eodhd_sql.py; 73 rows.

CREATE TABLE IF NOT EXISTS eodhd_exchange_codes (
    code          TEXT PRIMARY KEY,
    name          TEXT NOT NULL,
    operating_mic TEXT,
    country       TEXT NOT NULL,
    currency      TEXT NOT NULL,
    country_iso2  TEXT NOT NULL DEFAULT '',
    country_iso3  TEXT NOT NULL DEFAULT ''
);

INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('US', 'USA Stocks', 'XNAS, XNYS, OTCM', 'USA', 'USD', 'US', 'USA') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('LSE', 'London Exchange', 'XLON', 'UK', 'GBP', 'GB', 'GBR') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('NEO', 'NEO Exchange', 'NEOE', 'Canada', 'CAD', 'CA', 'CAN') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('V', 'TSX Venture Exchange', 'XTSX', 'Canada', 'CAD', 'CA', 'CAN') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('TO', 'Toronto Exchange', 'XTSE', 'Canada', 'CAD', 'CA', 'CAN') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('BE', 'Berlin Exchange', 'XBER', 'Germany', 'EUR', 'DE', 'DEU') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('HM', 'Hamburg Exchange', 'XHAM', 'Germany', 'EUR', 'DE', 'DEU') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('XETRA', 'XETRA Stock Exchange', 'XETR', 'Germany', 'EUR', 'DE', 'DEU') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('DU', 'Dusseldorf Exchange', 'XDUS', 'Germany', 'EUR', 'DE', 'DEU') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('F', 'Frankfurt Exchange', 'XFRA', 'Germany', 'EUR', 'DE', 'DEU') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('MU', 'Munich Exchange', 'XMUN', 'Germany', 'EUR', 'DE', 'DEU') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('STU', 'Stuttgart Exchange', 'XSTU', 'Germany', 'EUR', 'DE', 'DEU') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('HA', 'Hanover Exchange', 'XHAN', 'Germany', 'EUR', 'DE', 'DEU') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('LU', 'Luxembourg Stock Exchange', 'XLUX', 'Luxembourg', 'EUR', 'LU', 'LUX') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('VI', 'Vienna Exchange', 'XWBO', 'Austria', 'EUR', 'AT', 'AUT') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('PA', 'Euronext Paris', 'XPAR', 'France', 'EUR', 'FR', 'FRA') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('BR', 'Euronext Brussels', 'XBRU', 'Belgium', 'EUR', 'BE', 'BEL') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('LS', 'Euronext Lisbon', 'XLIS', 'Portugal', 'EUR', 'PT', 'PRT') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('MC', 'Madrid Exchange', 'BMEX', 'Spain', 'EUR', 'ES', 'ESP') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('AS', 'Euronext Amsterdam', 'XAMS', 'Netherlands', 'EUR', 'NL', 'NLD') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('SW', 'SIX Swiss Exchange', 'XSWX', 'Switzerland', 'CHF', 'CH', 'CHE') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('ST', 'Stockholm Exchange', 'XSTO', 'Sweden', 'SEK', 'SE', 'SWE') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('OL', 'Oslo Stock Exchange', 'XOSL', 'Norway', 'NOK', 'NO', 'NOR') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('HE', 'Helsinki Exchange', 'XHEL', 'Finland', 'EUR', 'FI', 'FIN') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('CO', 'Copenhagen Exchange', 'XCSE', 'Denmark', 'DKK', 'DK', 'DNK') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('IC', 'Iceland Exchange', 'XICE', 'Iceland', 'ISK', 'IS', 'ISL') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('IR', 'Irish Exchange', 'XDUB', 'Ireland', 'EUR', 'IE', 'IRL') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('PR', 'Prague Stock Exchange', 'XPRA', 'Czech Republic', 'CZK', 'CZ', 'CZE') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('EGX', 'Egyptian Exchange', 'NILX', 'Egypt', 'EGP', 'EG', 'EGY') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('GSE', 'Ghana Stock Exchange', 'XGHA', 'Ghana', 'GHS', 'GH', 'GHA') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('XBOT', 'Botswana Stock Exchange', 'XBOT', 'Botswana', 'BWP', 'BW', 'BWA') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('XNAI', 'Nairobi Securities Exchange', 'XNAI', 'Kenya', 'KES', 'KE', 'KEN') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('XNSA', 'Nigerian Stock Exchange', 'XNSA', 'Nigeria', 'NGN', 'NG', 'NGA') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('BC', 'Casablanca Stock Exchange', 'XCAS', 'Morocco', 'MAD', 'MA', 'MAR') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('SEM', 'Stock Exchange of Mauritius', 'XMAU', 'Mauritius', 'MUR', 'MU', 'MUS') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('MSE', 'Malawi Stock Exchange', 'XMSW', 'Malawi', 'MWK', 'MW', 'MWI') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('RSE', 'Rwanda Stock Exchange', 'RSEX', 'Rwanda', 'RWF ', 'RW', 'RWA') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('DSE', 'Dar es Salaam Stock Exchange', 'XDAR', 'Tanzania', 'TZS', 'TZ', 'TZA') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('USE', 'Uganda Securities Exchange', 'XUGA', 'Uganda', 'UGX', 'UG', 'UGA') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('LUSE', 'Lusaka Stock Exchange', 'XLUS', 'Zambia', 'ZMW', 'ZM', 'ZMB') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('TA', 'Tel Aviv Stock Exchange', 'XTAE', 'Israel', 'ILS', 'IL', 'ISR') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('XZIM', 'Zimbabwe Stock Exchange', 'XZIM', 'Zimbabwe', 'ZWL', 'ZW', 'ZWE') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('VFEX', 'Victoria Falls Stock Exchange', 'VFEX', 'Zimbabwe', 'ZWL', 'ZW', 'ZWE') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('KQ', 'KOSDAQ', 'XKOS', 'Korea', 'KRW', 'KR', 'KOR') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('KO', 'Korea Stock Exchange', 'XKRX', 'Korea', 'KRW', 'KR', 'KOR') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('WAR', 'Warsaw Stock Exchange', 'XWAR', 'Poland', 'PLN', 'PL', 'POL') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('PSE', 'Philippine Stock Exchange', 'XPHS', 'Philippines', 'PHP', 'PH', 'PHL') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('BUD', 'Budapest Stock Exchange', 'XBUD', 'Hungary', 'HUF', 'HU', 'HUN') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('KAR', 'Karachi Stock Exchange', 'XKAR', 'Pakistan', 'PKR', 'PK', 'PAK') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('SN', 'Chilean Stock Exchange', 'XSGO', 'Chile', 'CLP', 'CL', 'CHL') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('AU', 'Australian Securities Exchange', 'XASX', 'Australia', 'AUD', 'AU', 'AUS') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('SHE', 'Shenzhen Stock Exchange', 'XSHE', 'China', 'CNY', 'CN', 'CHN') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('AT', 'Athens Exchange', 'ASEX', 'Greece', 'EUR', 'GR', 'GRC') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('SHG', 'Shanghai Stock Exchange', 'XSHG', 'China', 'CNY', 'CN', 'CHN') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('JK', 'Jakarta Exchange', 'XIDX', 'Indonesia', 'IDR', 'ID', 'IDN') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('JSE', 'Johannesburg Exchange', 'XJSE', 'South Africa', 'ZAR', 'ZA', 'ZAF') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('BK', 'Thailand Exchange', 'XBKK', 'Thailand', 'THB', 'TH', 'THA') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('CM', 'Colombo Stock Exchange', 'XCOL', 'Sri Lanka', 'LKR', 'LK', 'LKA') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('VN', 'Vietnam Stocks', 'XSTC', 'Vietnam', 'VND', 'VN', 'VNM') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('KLSE', 'Kuala Lumpur Exchange', 'XKLS', 'Malaysia', 'MYR', 'MY', 'MYS') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('BA', 'Buenos Aires Exchange', 'XBUE', 'Argentina', 'ARS', 'AR', 'ARG') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('RO', 'Bucharest Stock Exchange', 'XBSE', 'Romania', 'RON', 'RO', 'ROU') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('SA', 'Sao Paulo Exchange', 'BVMF', 'Brazil', 'BRL', 'BR', 'BRA') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('MX', 'Mexican Exchange', 'XMEX', 'Mexico', 'MXN', 'MX', 'MEX') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('ZSE', 'Zagreb Stock Exchange', 'XZAG', 'Croatia', 'EUR', 'HR', 'HRV') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('FOREX', 'FOREX', 'CDSL', 'Unknown', 'Unknown', '', '') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('TWO', 'Taiwan OTC Exchange', 'ROCO', 'Taiwan', 'TWD', 'TW', 'TWN') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('TW', 'Taiwan Stock Exchange', 'XTAI', 'Taiwan', 'TWD', 'TW', 'TWN') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('CC', 'Cryptocurrencies', 'CRYP', 'Unknown', 'USD', '', '') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('LIM', 'Bolsa de Valores de Lima', 'XLIM', 'Peru', 'PEN', 'PE', 'PER') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('GBOND', 'Government Bonds', NULL, 'Unknown', 'Unknown', '', '') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('MONEY', 'Money Market Virtual Exchange', NULL, 'Unknown', 'Unknown', '', '') ON CONFLICT (code) DO NOTHING;
INSERT INTO eodhd_exchange_codes (code, name, operating_mic, country, currency, country_iso2, country_iso3) VALUES ('EUFUND', 'Europe Fund Virtual Exchange', NULL, 'Unknown', 'EUR', '', '') ON CONFLICT (code) DO NOTHING;
